- pyrtl/rtllib/aes.py
- tests/rtllib/test_aes.py
AES looks like it is finally cleaned up to be merged back into the main trunk.
The code is much cleaner than what we started out with
Also, both the combinatorial and the state machine decryption blocks are functional. I do not think that encryption is needed before we merge back into trunk.
@timsherwood What do you think?
> Add AES back into the development trunk

- pyrtl/helperfuncs.py
- pyrtl/passes.py
- pyrtl/transform.py
- tests/test_passes.py
Should resolve https://github.com/UCSBarchlab/PyRTL/issues/116
Handles synthesis of `*`, `+`, `-`, `x`, `=`, `<`, and `>` in terms of lower-level operations.
Includes new tests for synthesis of multiplexing, multiplication, and comparisons.
> Synthesis of high-level operations using net_transform

- index.html
> Minor typo in index.html

- pyrtl/rtllib/multipliers.py
- tests/rtllib/test_multipliers.py
Added new type of multiplier that shift-adds multiple (parameterized) times per clock cycle.
Also added unit tests for the new multiplier (`complex_mult()`).
> New multiplier w/ tests

- pyrtl/core.py
- pyrtl/helperfuncs.py
Added `ProbeIndexer(NameIndexer)` and `AssertIndexer(NameIndexer)` for use in `probe()` and `rtl_assert()`, respectively.
> Finished remaining parts of issue #152

- pyrtl/rtllib/aes.py
(cherry picked from commit d03587c)
> AES fixes for original attempt at issue #193

- pyrtl/inputoutput.py
- tests/test_inputoutput.py
(made new branch to fix double-commit branch from before)
> Fixed net_graph() unused wires problem (issue #204) and added a test for it

- pyrtl/simulation.py
- tests/test_conditional.py
- tests/test_helperfuncs.py
- tests/test_passes.py
- tests/test_simulation.py
> Improved print_trace() with spacing and new parameters, tests

- pyrtl/core.py
- tests/test_core.py
in new test class `TestSanityCheckNet`
> Added unit tests for sanity_check_net()

- pyrtl/inputoutput.py
- tests/test_inputoutput.py
iPynb typed files can now display output in the WaveDrom format. See: http://wavedrom.com/
> WaveDrom renders in Jupyter

- pyrtl/inputoutput.py
As I was trying to understand the graph structure of some circuits, I noticed that inputs/outputs/consts weren't connected to the graph. In addition, it was a little difficult to understand what some of the nodes do (select, buf), so I changed some shapes, colors, and names to make it easier to read.
The bug fixed ([Line 419](https://github.com/UCSBarchlab/PyRTL/compare/development...pllab:graphviz?expand=1#diff-c18524de449e49323ee4ea311060d299R419)) is connecting the inputs/outputs/consts; the rest are cosmetic changes that can be removed if they prove too controversial.
Given this code:
```python
import pyrtl
i = pyrtl.Input(8, 'i')
a = pyrtl.Register(8, 'a')
b = pyrtl.Output(8, 'b')
a.next <<= a + i + 2
b <<= a
sim.step_multiple({'i': [1,2,3,4,5]}, nsteps=5) …
```
> Fix unconnected input/output/consts when outputting to graphviz

- pyrtl/core.py
- tests/test_core.py
As I was examining the netlist, I thought it would be nice to have a sanity check added about the number of destinations a net is allowed (1, except in the `@` case; the check for `@` already existed), as well as a sanity check ensuring that the output of a `r` net always is connected to a `Register` wire vector. This adds the checks and some unit tests.
> add some sanity checks related to net dests

- tests/test_signed.py
Fixes duplicate test names that were being ignored by nose2.
> Updating some tests

- .github/workflows/python-package.yml
- tox.ini
This integrated GitHub actions for CI. It takes advantage of the `tox-gh-actions` tox plugin for automatically running the stuff we have in `tox.ini`.
You can see success of it [here](https://github.com/pllab/PyRTL/actions/runs/626778391).
> GitHub actions

- pyrtl/inputoutput.py
This PR improves how bit selects are presented in graphviz.
For example, given the following code:
```python
import pyrtl
a = pyrtl.Input(32, 'a')
b = pyrtl.Output(32, 'b')
c = pyrtl.Output(5, 'c')
d = pyrtl.Output(4, 'd')
w = a[0:20:3]  # slice with custom step
b <<= pyrtl.mux(0, w, 1)
c <<= w[2:6] & (a[0] ^ 1)
d <<= w[4:6] ^ 4
with open("test1.svg", "w") as f:
pyrtl.output_to_svg(f)
```
Previously we had:
And now we have:
For non-consecutive selected bits, the word 'bits' is displayed. Other choices we can change that to in the future are 'slice' or 'select', for example.
It also does a small improvement on memory display, by including the user-defined name if present.
Before:
After:
> Improve how bit selects and memory ops are presented in graphviz

- pyrtl/passes.py
- pyrtl/transform.py
- tests/test_transform.py
The main contribution of this PR is adding documentation and tests for `replace_wire_fast`. I'm currently investigating the correctness of `replace_wire`, which I've consistently had issues using and so have had to revert to my own custom passes.
> Adding documentation and some tests for the passes and transforms

- pyrtl/__init__.py
- pyrtl/analysis.py
- pyrtl/visualization.py
- tests/test_analysis.py
This PR adds two functions, `paths` and `distance`, for easily getting a list of paths between one or more sources and one more destinations.
> Some basic graph-related algorithms

- pyrtl/rtllib/matrix.py
- tests/rtllib/test_matrix.py
Also improves some docstring wording, and adds associated tests.
> Move matrix helper to main matrix file; add more error detection on hstack/vstack

- pyrtl/importexport.py
- tests/test_importexport.py
Some ISCAS bench files have input and output wires with the same name. This PR adds a fix to handle then in import, by renaming the output wire when needed (an alerting the user if that's the case).
> Rename ISCAS bench output wires if also an input

- pyrtl/passes.py
- tests/test_passes.py
PyRTL often creates unneeded slice nets implicitly when ensuring correct wire sizing between nets:
As a small example:
That left slice, `[3:0]`, is unneeded, since `tmp0` is 4 bits wide, and the slide is getting `tmp0`'s bits from MSB to LSB. This PR checks for exactly such cases, so it can be removed:
As a larger example:
There are a long chain of `[3:0]` slices, all of which can be replaced with the originator of the first `[3:0]` slice, respectively.
This PR removes such chains, so that the above example now becomes:
This optimization is added as part of `pyrtl.optimize()`.
> Add optimization pass that removes unneeded slices

- ipynb-examples/example7-synth-timing-draft.ipynb
- ipynb-examples/example8-verilog.ipynb
Minor changes to jupyter notebook example code.
> fixed references to estimate.py code

- .coveragerc
- .github/workflows/python-package.yml
- tox.ini
Enables code coverage, and sets up the Github action to push the report to codecove.io.
> Enable code coverage

- pyrtl/importexport.py
- tests/test_importexport.py
To match the automatic insertion of reset logic recently added to `output_to_verilog()`, this also adds it to `output_verilog_testbench()`.
We also error out if `add_reset` is not False and a wire named `rst` exists in the design.
> Add add_reset to verilog test bench generation, and add check for existing `rst` wire.

- pyrtl/importexport.py
- tests/test_importexport.py
The set of covers that BLIF import supported was previously hard-coded. This PR adds a way to programmatically add in the on-set covers that don't match PyRTL-recognized primitives (though it is now generic enough to handle those too), by simply doing the conjunction of the disjunctions in the cover.
Because of this, we can remove some of the one-off checks that aren't needed. This also adds more tests for sanity.
> Simplify BLIF cover import to be more programmatic

- pyrtl/passes.py
Simple update to pass the `skip_sanity_check` flag given to `optimize()` to the sub-passes that currently call `sanity_check()`.
> Feed sanity check flag during optimization to subpasses

- pyrtl/simulation.py
- pyrtl/visualization.py
Reorder None check for clarity (made in #390).
> Small adjustment for code clarity

- tests/rtllib/test_matrix.py
> Update matrix tests to be clearer about where the exception-causing errors occur
