UCSBarchlab/PyRTL

- pyrtl/wire.py
- tests/test_wire.py
This makes the parsing of Verilog-style consts match more closely with actual Verilog behavior, and removes the dependence on the specifics of Python syntax as parsed by `int(x, 0)`.
> Fix issue #118 with support for h, d, negatives, and underscores in string Consts

- pyrtl/inputoutput.py
Just a quick bugfix so that `OutputToVerilog` will include an `initial begin` block with the values of a ROM. There was already code to do this, but it was looking for a nonexistent `initialdata` attribute.
> Fix RomBlock values in Verilog output

- pyrtl/helperfuncs.py
- tests/test_helperfuncs.py
1. Added unittests and more elaborate docstrings for `wirevector_list` and derived functions
2. This includes a small bugfix: when custom bitwidths were passed using the `'name/bw'` syntax, they were passed on as string and not yet cast to integer.
3. `names` and `bitwidth` now also accept lists as input.
- I kept the `'name/bw'` syntax intact, backwards compatibility is not broken.
- Some additional unittests have been added for the new functionality
> Expanded functionality for `pyrtl.helperfuncs.wirevector_list()`: now accepting list arguments

- pyrtl/compilesim.py
- pyrtl/simulation.py
- tests/test_compilesim.py
- tests/test_simulation.py
These commits add several unit tests to cover both normal flow and error edge cases of 'step_multiple', fixes some bugs revealed in the process, adds additional functionality (like being able to stop simulation after the first encountered error, or specifying the number of steps to simulate independent of given input values), and adds 'step_multiple' to 'compilesim.py'. It may be that this function can be extracted into one helper function that is shared amongst Simulation, FastSimulation, and CompiledSimulation (passing in various inspect and step functions as arguments to make it shareable) but that can be left for another day. Right now the format matches how the *Simulation classes are currently defined.
> Improvements to step_multiple

- pyrtl/core.py
- pyrtl/memory.py
- pyrtl/wire.py
- tests/test_core.py
- tests/test_memblock.py
- tests/test_simulation.py
This adds the ability to get a reference to a memory created internally to any function/block (as long as you have its name)
This useful for when a block defines its own internal memory block, and during simulation you want to instantiate that memory with certain values for testing. Since the Simulation constructor requires a reference to the memory object itself, but the block your testing defines the memory internally, this allows you to get the object reference.
Note that this requires you know the name of the memory block, meaning that you most likely need to have named it yourself.
This version manipulates the working block in order to store and get these memory block references. [Another pull request](https://github.com/UCSBarchlab/PyRTL/pull/277) uses Python introspection and a …
> Add ability to get handle to internally-defined memories (for use in Simulation) (Version 1)

- pyrtl/verilog.py
Fixes bug where internal names in Verilog design under test don't match the names referenced by the test bench. Also adds the ability to automatically include a file in the test bench (with the intention being this file contains the top level module being tested by the test bench).
No unittests were added, but I was able to test this creating and testing Verilog in my own PyRTL-to-Verilog workflow.
> Minor fixes to Verilog testbench output

- pyrtl/simulation.py
Before this change, the `render_trace()` method would print leading spaces before the trace based on the length of the longest wire name, even if that wire wasn't included in the outputted trace. This fix bases the number of leading spaces on the trace_list. It's safe to use the trace_list because is made sure to be set in line 1188.
Given
```
sim.tracer.render_trace(symbol_len=6, trace_list=['reset', 'data_in', 'valid_in', 'ready_in', 'data_out', 'valid_out', 'ready_out'])
```
Before change:
After change:
Also made sure if still works if no trace_list is specified.
Given
```
sim.tracer.render_trace()
```
it emits
(Also minor clean up in comparison in line 802; Python continually complained whenever I run code from this file prior to that fix).
> small adjustment to rendered trace, so that it doesn't print leading spaces when trace_list is specified with shorter wire names

- pyrtl/core.py
- pyrtl/helperfuncs.py
- pyrtl/passes.py
There are two semi-related changes here, the first of which is (hopefully) uncontroversial, and a third minor change.
The first changes references to `debug_mode` outside of `core.py` to be function calls (and adds a new function `_get_debug_mode()` for calling). This is needed because when a global variable is imported like `from .core import debug_mode`, a new copy of that variable is created for just that module, i.e.
```
from .core import debug_mode
```
is the same as
```
import core
debug_mode = core.debug_mode
```
We can't just replace `debug_mode` with `core.debug_mode` because `import core` is illegal syntax in this case. Please let me know if there's a better way of doing this.
I tested this by observing that given the following code:
```
pyrtl.set_debug_mode(debug=True)
... …
```
> fix access to debug_mode global variable, silence Probe stack info when not in debug mode

- pyrtl/core.py
When importing BLIFs into PyRTL, I've had several experiences where the BLIF cannot be imported properly because some of the wires declared as outputs are also used as arguments to nets throughout the BLIF netlist. The proposed changes add information about exactly which wires are being misused this way in the reported error, making fixing the aforementioned problem (and hopefully the normal in-PyRTL development workflow) a little easier.
Example of what it looks like now (last line with 'ready_o'):
> print wire names in error when they are inputs or outputs are misused

- index.html
Fixes typos, capitalization, and GCD graphviz visualization.
Here's the GCD picture that will be added (actual image is being added to a master branch folder, like the other images used in the website). This is the GCD described in one of the examples currently on the website itself.
> Fixes typos, capitalization and adds GraphViz example to website

- pyrtl/inputoutput.py
- tests/test_inputoutput.py
As I was trying to correlate the textual timing information produced by `TimingAnalysis().timing_map` with the visual graph of the circuit produced by `output_to_graphviz()`, I thought it would helpful if a user could specify an edge-namer function when creating the the namer function that `output_to_graphviz()` accepts. This change decomposes the `graphviz_default_namer` function to accept both a `node_namer` function and an `edge_namer` function (using the defaults that were present already).
For example, now I can do this:
```python
timing = analysis.TimingAnalysis()
def graph_namer(t, i, j):
edge_namer = pyrtl.inputoutput.detailed_edge_namer(timing.timing_map)
return pyrtl.inputoutput.graphviz_default_namer(t, i, j, edge_namer=edge_namer)
with open(f"{name}.dot", "w+") as f: …
```
> Decomposes graphviz default namer to accept a custom edge namer function and custom node namer function

- pyrtl/__init__.py
- pyrtl/wire.py
- tests/test_simulation.py
- tests/test_wire.py
This creates a Bundle class, which is a subclass of WireVector. The main purpose is to provide handy read access of particular parts of a wire by giving these parts field names.
Create a Bundle object by supplying either
* A list of (field name, width) tuples
```python
rformat = [("funct7", 7), ("rs2", 5), ("rs1", 5), ("funct3", 3), ("rd", 5), ("opcode", 7)]
w = pyrtl.Bundle(rformat)
```
* A dictionary mapping field names to widths
```python
rformat = {"funct7": 7, "rs2": 5, "rs1": 5, "funct3": 3, "rd": 5, "opcode": 7}
w = pyrtl.Bundle(rformat)
```
* A class whose sole attributes are widths of fields to be used
```python
class RFormat:
funct7 = 7
rs2 = 5
rs1 = 5
funct3 = 3
rd = 5
opcode = 7
w = pyrtl.Bundle(RFormat)
```
In any of the above cases, the following should work:
```python
w <<= …
```
> Adding a Bundle class for naming parts of wires

- examples/example3-statemachine.py
- examples/introduction-to-hardware.py
- pyrtl/analysis/estimate.py
- pyrtl/conditional.py
- pyrtl/core.py
- pyrtl/corecircuits.py
- pyrtl/helperfuncs.py
- pyrtl/inputoutput.py
- pyrtl/memory.py
- pyrtl/passes.py
- pyrtl/rtllib/muxes.py
- pyrtl/simulation.py
- pyrtl/transform.py
- pyrtl/wire.py
- tests/rtllib/test_muxes.py
- tests/test_simulation.py
- tests/test_wire.py
Fixes various typos and more importantly some tox issues (pep8, pylint, and some 2.7 test compatibility issues by adding usage of `six` where appropriate). The 2.7 compatibility issues fixed here weren't syntactic (so the code in the current development branch still runs for 2.7), but the additional fixes here make the tests more robust to reflect when 2.7 is being run so the correct exception is caught, and uses `six.callable` rather than `type` in the Bundle `get_fields` method.
> Fixing typos, pep8, pylint, and some 2.7 test compat issues

- pyrtl/analysis/estimate.py
- pyrtl/core.py
- pyrtl/helperfuncs.py
- pyrtl/simulation.py
While working on retiming, it's been useful to view the netlist and critical paths. I noticed that it was always printing the edges using Latex notation, even when I wasn't in a Jupyter notebook. The changes are:
* Changes `_currently_in_ipython` to `_currently_in_jupyter_notebook`, replacing the check for `__IPYTHON__` with a more specific check to see if the current terminal is the one used by Jupyter (since `__IPYTHON__` is true when running `ipython` at the terminal and in Jupyter, and we only really care if we're in Jupyter for displaying that Latex notation)
* Uses `_currently_in_jupyter_notebook` throughout PyRTL for consistency, replacing the ad-hoc checks for ipython importability (which wouldn't fail even when in a regular terminal)
* Creates a function `_print_netlist_latex` …
> Fix block netlist and critical paths display when in Jupyter notebook vs Python/IPython

- pyrtl/memory.py
- pyrtl/verilog.py
- pyrtl/wire.py
- tests/test_inputoutput.py
- tests/test_verilog.py
There are two major changes:
* The `output_to_verilog` function is now deterministic, in that it prints the wires/memories/registers/connections in the order every time (by making sure to sort the appropriate wire or net list before iterating).
* Adds a test comparing the actual Verilog file produced to the expected file.
Other minor things included: moved the Verilog tests to a separate file to match how the implementation is in a separate file, and added helper functions to be able to reset the name indexers to be able to have completely predictable automatic names produced regardless of where the test is run.
Fixes #216.
Fixes #293.
I added a new test in `test_verilog.py`, so that should pass (along with everything else in `tox`).
> Make Verilog output deterministic by sorting wires and nets

- pyrtl/verilog.py
- tests/test_verilog.py
While the previous approach of emitting Verilog was still consistent, this approach changes it so memory declarations and computations are outputted based on the memory's **id** instead. This is nicer because the actual name outputted to Verilog is based on the memory's id, rather than the name, so it makes the output even easier to follow.
Also changes name of test to reflect that the Verilog output test tests consistency, rather than correctness, right now.
> Sort memories by id rather than name in Verilog output

- pyrtl/compilesim.py
- tests/test_compilesim.py
This is a minor change, but helpful nonetheless. It fixes an edge case in `compilesim.py` where the given mapping for a memory's initial values is empty. Currently it crashes in such cases because it tries to take the `max` of that dictionary, which would be empty. This adds a check for emptiness beforehand.
It now matches the behavior of `simulation.py`, which only accesses these mappings if present/non-empty.
> Don't crash in compiledsim when initial memory values are empty

- pyrtl/compilesim.py
- tests/test_compilesim.py
- tests/test_simulation.py
For each MemBlock in a design, the current `CompiledSimulation` class allocates a static array large enough to hold all the elements of that MemBlock. This approach fails when the MemBlock's address width is about greater than 30, because that means the DLL created will contain huge statically allocated arrays; for a 32-bit address width, the array has size 2^32 * (size of elements) bytes. The resulting DLL is around ~4 GB in size, which 1) is huge and 2) either fails linking or silently compiles incorrectly (I've seen both cases).
This change replaces the static arrays in the DLL with hashmaps. This has the advantage of only creating memory entries on write, so the resultant DLL is kilobytes, rather than gigabytes, in size, with only the slight disadvantage at runtime for lookup compared …
> Make compilesim significantly more efficient for designs with large memblocks

- pyrtl/__init__.py
- pyrtl/inputoutput.py
- tests/test_inputoutput.py
This PR does a few things:
1. It cleans up the graphviz detailed namers, making it easier to use by 1) augmenting the existing default namers with my previous detailed namer changes and more importantly 2) exposing a `detailed_graphviz_namer`, which takes in `extra_edge_info` and `extra_node_info` maps. I feel that it's now easier to add custom information next to each node and edge.
2. It adds an option to the graphviz namers to not split the state. This merely exposes the `split_state` argument that was previously always hard-coded in the `net_graph` calls from `block_to_graphviz_string`/`output_to_trivialgraph`.
So now, whereas before the graphviz would always look like:
It can now look like this when `split_state=False` is passed to `output_to_graphviz`:
3. It adds an `output_to_svg` …
> Various updates to inputoutput functions

- .coveragerc
- .gitignore
This is a quick fix to the coverage-related framework. The html coverage information is put in `htmlcov`, not `htmlconv`, and we need to ignore `.tox/` contents when reporting.
Before:
After:
> Correct and git ignore htmlcov coverage output folder; don't report on .tox contents

- pyrtl/core.py
As I've been writing netlist transformations, it's been helpful to have additional information when I (often) make the mistake of creating wires with multiple drivers. This change prints out the nets that are causing the problem. This is especially useful in conjunction with `pyrtl.set_debug_mode()` since the net argument wire names will include the line number of the one of the offending assignments.
Given this (in the code I'm writing, the problem isn't usually so obvious):
```
import pyrtl
pyrtl.set_debug_mode()
a = pyrtl.Output(2, 'a')
b, c = pyrtl.input_list('b/2 c/2')
a <<= b + 1
a <<= c + 1
```
before it would just print:
```
pyrtl.pyrtlexceptions.PyrtlError: Wire "a/2O" has multiple drivers (check for multiple assignments with "<<=" or accidental mixing of …
```
> Make error message for multiple drivers more helpful

- pyrtl/compilesim.py
- pyrtl/simulation.py
- tests/test_compilesim.py
- tests/test_simulation.py
`step_multiple` has been changed so that the `provided_inputs` argument doesn't need to be supplied when there are no inputs to supply (versus previously, you would need to supply an empty map, `{}`). When it's not supplied, it requires that `nsteps` be specified instead. This is useful for testing designs without inputs (of which I've made a few recently, so this shorthand is useful).
I.e. you can do this:
```
import pyrtl
r = pyrtl.Register(2, 'r')
r.next <<= r + 1
sim.step_multiple(nsteps=10)  # previously needed to be `sim.step_multiple({}, nsteps=10)`
sim.tracer.render_trace()
```
producing
```
▏0                        ▏5                       
r 0x0  ╳0x1 ╳0x2 ╳0x3 ╳0x0  ╳0x1 ╳0x2 ╳0x3 ╳0x0 ╳0x1 
```
> Make step_multiple parameters more descriptive, remove need for inputs when appropriate

- pyrtl/compilesim.py
- pyrtl/simulation.py
- tests/test_compilesim.py
There was an edge case that wasn't covered in the normal Simulation/SimulationTrace workflow: when a CompiledSimulation is instantiated, it creates a SimulationTrace if needed, followed by removing all untraceable wires from the trace list (in the CompiledSimulation's case, non-Input/Output wires or non-probes for Output wires). If a named register, for example, was part of the original trace list, the SimulationTrace object would be created fine, but after removing untraceable wires, the trace list would be empty. Then during rendering, it would throw a non-PyRTL exception.
This fixes that as well as adds a note about untraceable wires in CompiledSimulation's documentation.
See the added test for an example.
> Add check in simulation trace render for empty trace list

- pyrtl/verilog.py
- tests/test_verilog.py
This simple change cleans up Verilog output by removing the section for register updates if there are no registers in the design, as well as removes an unneeded empty line when possible.
> small update on verilog output

- pyrtl/__init__.py
- pyrtl/inputoutput.py
- pyrtl/passes.py
- pyrtl/verilog.py
- tests/test_inputoutput.py
- tests/test_passes.py
- tests/test_verilog.py
As I was looking at other output formats/IRs, I found that the FIRRTL output created by PyRTL is wrong, specifically with concatenation and select.
The problem with concatenation is that the FIRRTL creation code was assuming that the PyRTL `c` nets only had two argument wires, when in reality the number of wires is arbitrary.
Given the following PyRTL code:
```python
i = pyrtl.Const(0b1100)
j = pyrtl.Const(0b011, bitwidth=3)
k = pyrtl.Const(0b100110)
o = pyrtl.Output(13, 'o')
o <<= pyrtl.concat(i, j, k)
sim.step({})
assert sim.inspect('o') == 0b1100011100110
```
`output_to_firrtl()` was creating:
```firrtl
circuit Example : 
module Example : 
input clock : Clock
input reset : UInt<1>
output o : UInt<13>
node const_2_38 = UInt<6>(38)
node const_0_12 = UInt<4>(12) …
```
> Fix firrtl concat and select

- pyrtl/inputoutput.py
This is a minor follow-on to the recent FIRRTL output update, adding in the passed in block to the net transform calls.
> Add block to net transform calls in firrtl output call

- pyrtl/inputoutput.py
Slight internal update to graphviz edge namer, to always output edge info for an edge if it's present in the user-provided map.
E.g. I have an edge namer that prints the type of edge/wire next to the wire. Given the following PyRTL:
```python
import pyrtl
a = pyrtl.Input(2, 'a')
b = pyrtl.Input(2, 'b')
c = pyrtl.Output(3, 'c')
c <<= a + b - 1
info = {e: e.name + str(type(e)) for e in pyrtl.working_block().wirevector_set}
namer = pyrtl.inputoutput.graphviz_detailed_namer(extra_edge_info=info)
with open("graph-out.gv", "w") as f:
pyrtl.output_to_graphviz(f, namer=namer, split_state=False)
```
Before, it wouldn't print it out for inputs/constants/outputs:
and the new version:
> Output extra edge info always when present in map

- pyrtl/helperfuncs.py
This updates the Latex output for the block when outputting in a Jupyter Notebook. In [this](https://github.com/pllab/PyRTL/commit/83706f0b8b225421872e257ba47e8b013877dcbb#diff-152e4130145ecb83900318841908b034000d6a2842964a8a6be46fcac6f61f3eR668) commit I mistakenly prefixed the string with `r` to appease `tox`. This commit fixes the problem:
Before:
After:
> Fix textual netlist output in jupyter notebooks

- pyrtl/simulation.py
- tests/test_simulation.py
A small error occurs when using FastSimulation when they're are Consts that were created using an IntEnum.
For example, given:
```python
from enum import IntEnum
import pyrtl
class Causes(IntEnum):
BadAddress = 0
IllegalInstruction = 1
Timeout = 3
i = pyrtl.Input(max(Causes).bit_length(), 'i')
o = pyrtl.Output(1, 'o')
with pyrtl.conditional_assignment:
with (i == Causes.BadAddress) | (i == Causes.IllegalInstruction):
o |= 0
with pyrtl.otherwise:
o |= 1
sim = pyrtl.FastSimulation()
sim.step_multiple({
'i': [v for v in Causes]
})
sim.tracer.render_trace()
```
The error that is occurs is:
```bash
Traceback (most recent call last):
File "ex1.py", line 18, in <module>
sim.step_multiple({
File "/Users/michael/PyRTL/pyrtl/simulation.py", line 632, in step_multiple
self.step({w: int(v[i]) for w, …
```
> Fix FastSimulation to work with IntEnums

- pyrtl/inputoutput.py
This is adds an option to not split the register logic nets in the SVG output, as was done previously for trivial graph and graphviz formats.
```python
with open("foo.svg", "w") as f:
pyrtl.output_to_svg(f, split_state=False)
```
> Exposing split_state option for SVG output, like previously done for trivialgraph

- pyrtl/simulation.py
The issue is the following: PyRTL currently doesn't officially support explicitly-named constants, but you can easily give them a new name after creation:
```python
c = pyrtl.Const(1)
c.name = "my_constant"
```
Disregarding the fact that doing this probably breaks the `wirevector_by_name` map that is stored in the block for performance reasons (officially supported named Constants would be another PR), doing the above currently works in Simulation and CompiledSimulation, but breaks FastSimulation.
This PR updates FastSimulation to behave like the other two simulation frameworks in this edge case.
Given this
```python
from enum import IntEnum
import pyrtl
if __name__ == "__main__":
i = pyrtl.Input(1, 'i')
o = pyrtl.Output(2, 'o')
c = pyrtl.Const(3)
c.name = "my_constant"
o <<= i + c
tracer …
```
> Make FastSimulation behave like Simulation and CompiledSimulation when named constants exist

- pyrtl/inputoutput.py
- pyrtl/simulation.py
- pyrtl/transform.py
- pyrtl/wire.py
- tests/test_simulation.py
- tests/test_transform.py
- tests/test_verilog.py
- tests/test_wire.py
This change officially allows constants to be given user-defined names.
The reasons why this might be desired:
* It's consistent with how we can name all other WireVectors and Memories
* Constants whose name have significant meaning (like archid, vendorid in the case of a RISC-V processor) will be reflected in various forms of output like Verilog and graphviz
* By being able to name constants explicitly, they will be automatically added to the traces (unless otherwise specified), again consistent with other WireVectors
One difference that might trip people up between naming constants and naming other wirevectors is that the name argument for constants is third, which I think is most natural (since the first argument is the constant value and the second is the bitwidth). The name follows …
> Adding option to name constants

- pyrtl/helperfuncs.py
- tests/test_helperfuncs.py
The following bit patterns would fail because `rtl_any` and `rtl_all` expect non-empty lists:
```python
pyrtl.match_bitpattern(r, '?1??1?')
pyrtl.match_bitpattern(r, '00??00')
```
This adds additional checks for non-empty `zeros_bits` and `ones_bits`. It also adds additional tests and adds a check for if invalid characters (characters that aren't 0, 1, ?, x, or X) are present.
> Fixing match_bitpattern for when pattern doesn't have either any zeroes, or any ones

- tests/test_inputoutput.py
Looks like a `print` call was left in a unit test. This simply removes it.
> Remove extraneous print in unit test

- tox.ini
tox-gh-actions isn't supported with Python 3.4. For simplicity, we'd like the tox.ini file to be fully supported by the gh-action flow, so this PR changes back the Python 3 version used for continuous integration to 3.7.
> GitHub actions update

- pyrtl/helperfuncs.py
- tests/test_helperfuncs.py
This PR expands the functionality of `match_bitpattern` to 1) return the fields that are matched when non-`?` characters are used as wildcards in the pattern and 2) allow the fields to be pattern-matched against tuples in `with` statements:
Here's a small example:
```python
import pyrtl
i = pyrtl.Input(5, 'i')
out = pyrtl.Output(2, 'out')
with pyrtl.conditional_assignment:
with pyrtl.match_bitpattern(i, '1a?a0') as (a,):
out |= a
with pyrtl.match_bitpattern(i, 'b0?1b') as (b,):
out |= b
with pyrtl.match_bitpattern(i, 'ba1ab') as (b, a):
out |= a + b
sim.step_multiple({
'i':   [0b11010, 0b00011, 0b01101]
}, {
'out': [0b11, 0b01, 0b11]
})
```
The function now returns NamedTuples for usability, and something important to note is that the order of the fields returned …
> Expand functionality of matching bitpattern to include fields

- pyrtl/__init__.py
- pyrtl/helperfuncs.py
- tests/test_helperfuncs.py
This adds tests to the recent `bitpattern_to_val` function, and exposes it via `__init__.py`.
> Adds tests for bitpattern_to_val

- pyrtl/helperfuncs.py
- tests/test_helperfuncs.py
Now you can add a field_map kw argument to `bitpattern_to_val`, so that you don't have to rely on single-character field names for the named_fields.
```python
field_map = {
's': 'rs2',
'r': 'rs1',
'd': 'rd',
'i': 'imm',
}
pyrtl.bitpattern_to_val(
'0000000sssssrrrrr000ddddd0110011', rs2=1, rs1=2, rd=3, field_map=field_map
)
```
> Adding a way to supply field_map to bitpattern_to_val

- pyrtl/passes.py
- pyrtl/transform.py
- tests/test_passes.py
When calling `pyrtl.synthesize()`, it previously always merged the IO wirevectors by inserting a series of slice nets to disassemble each input, and a single concat net to assemble each output. I think it's beneficial to have the option to *not* merge these IO vectors (for example, when emitting BLIF, you want the 1-bit IO).
This change adds the option to leave them unmerged by adding another argument to `pyrtl.synthesize()` (`merge_io_vectors=True`), defaulting to merging them like normal.
It also adds the information about the mapped IO, in either case, to the PostSynth block's `io_map`, which wasn't being used beforehand (but seems to have been initially added for this exact purpose).
> Add option to emit 1-bit io after synthesis, and track io_map in PostSynth block.

- pyrtl/passes.py
- pyrtl/simulation.py
This adds a few named-constant related changes from #321:
* During synthesis, retain name of const in newly generated wire
* Disallow simulation unless there is a non-Constant named wirevector, since constants don't change during simulation and so simulation wouldn't be useful (matches the previous behavior)
This adds the `synth` substring into synthesized constant names. Is this acceptable?
> Keep user-defined const name after synthesis; error in simulation if only named wires are Consts

- pyrtl/core.py
- pyrtl/passes.py
- pyrtl/transform.py
- tests/test_passes.py
This PR fixes a test I had added in #343 (checking for correctness of io mapping in PostSynth blocks), and now also tracks registers in a separate `reg_map`.
> Fix post-synth passes test; add reg_map for tracking registers post-synthesis

- pyrtl/conditional.py
- tests/test_conditional.py
Registers can currently be given a special property, `condition_default`, which is used for updating the wire in the branch of conditional update if it's not updated otherwise.
This PR's approach is an alternative approach, by allowing the user to set to the default wire update values at the beginning of the conditional assignment block, like so:
```python
r1 = pyrtl.Register(bitwidth=3, name='r1')
r2 = pyrtl.Register(bitwidth=3, name='r2')
r3 = pyrtl.Register(bitwidth=3, name='r3')
o = pyrtl.Output(bitwidth=3, name='o')
with pyrtl.conditional_assignment(
defaults={
r1: r1 + 2,
r2: 6,
o: 3
}):
with i < 2:
r1.next |= r1 + 1
o |= i
with i < 3:
r2.next |= r2 + 1
with pyrtl.otherwise:
r3.next |= 2
o |= 7
```
Note that like before, it works for both registers and normal wirevectors.
> A different way of specifying conditional defaults

- pyrtl/transform.py
- tests/test_transform.py
This is a fix for #348; see that issue for rationale.
> Updating `clone_wire` to be safe when used on same block.

- pyrtl/__init__.py
- pyrtl/transform.py
- tests/test_transform.py
`replace_wire` is incorrect, I believe. In [line 101](https://github.com/UCSBarchlab/PyRTL/compare/development...pllab:transform-cleanup?expand=1#diff-67c9ebb170eeb38059bfed23e32ad4d0f03cba3f757e8f2085c6e768ece6302fL101), it uses `new_src` when it should be using `new_dst`. In addition, iterating over `block.logic` in lines [85](https://github.com/UCSBarchlab/PyRTL/compare/development...pllab:transform-cleanup?expand=1#diff-67c9ebb170eeb38059bfed23e32ad4d0f03cba3f757e8f2085c6e768ece6302fL85) and [96](https://github.com/UCSBarchlab/PyRTL/compare/development...pllab:transform-cleanup?expand=1#diff-67c9ebb170eeb38059bfed23e32ad4d0f03cba3f757e8f2085c6e768ece6302fL96) causes alterations to `block.logic` in lines [92](https://github.com/UCSBarchlab/PyRTL/compare/development...pllab:transform-cle …
> Remove `replace_wire`, use `replace_wire_fast` instead; add tests and more documentation

- pyrtl/importexport.py
- tests/test_importexport.py
Makes sure verilog testbench output is deterministic by sorted wire names before printing them. Also cleans up Verilog output a tiny bit.
> Determinize verilog testbench output

- pyrtl/compilesim.py
- pyrtl/importexport.py
- pyrtl/simulation.py
- tests/test_importexport.py
Currently, the testbench produced by `output_verilog_testbench()` sets all registers and memory locations to 0, rather than the values they were initialized to when given a trace.
For example:
```python
import pyrtl
i = pyrtl.Input(2, 'i')
r1 = pyrtl.Register(4, 'r1')
r2 = pyrtl.Register(5)
r3 = pyrtl.Register(2)
m = pyrtl.MemBlock(4, 5)
r2.next <<= r1 + m[4]
m[4] <<= r3 * i
r1.next <<= m[3] + r3
r3.next <<= r1 - 1
sim = pyrtl.Simulation(register_value_map={
r1: 2,
r2: 7,
}, memory_value_map={
m: {
4: 11,
3: 7
}
})
sim.step_multiple({
'i': [0, 1, 2, 0, 2]  
}, nsteps=5)
sim.tracer.render_trace()
with open("tb.v", "w") as f:
pyrtl.output_verilog_testbench(f, sim.tracer)
```
produces the following testbench code:
```verilog
module tb();
reg clk;
reg[1:0] i;
integer tb_iter;
toplevel …
```
> Add ability to initialize registers and memories from trace when outputting Verilog testbench

- pyrtl/corecircuits.py
- tests/test_helperfuncs.py
Currently, shifting by an integer is not allowed in PyRTL. So instead of being able to do
```python
pyrtl.shift_left_logical(w, 2)
```
you currently have to do
```python
pyrtl.concat(w[:-2], pyrtl.Const(0, 2))
```
This PR allows shifting by an integer literal since the workaround is a little verbose/unintuitive.
Rather than causing a barrel shifter to be created in these cases, the PR uses an optimization that essentially checks for the integer literal cases, and in these cases, does a concatenation or slice as needed. Thus, the unoptimized netlist remains relatively clean.
For example, this given this code:
```python
i = pyrtl.Input(8, 'i')
o = pyrtl.Output(8, 'o')
o <<= pyrtl.shift_left_arithmetic(i, 2)  # or logical
```
using a barrel shifter would produce the following graphical …
> Allow integer shift amounts for shifter corecircuits

- pyrtl/visualization.py
- tests/test_visualization.py
When the same wire is the source to a particular net multiple times (e.g. a `c` net), `net_graph()`, and by extension all the graphical output functions that use it like `output_to_graphviz()`, don't properly display the additional edges.
For example, given:
```python
import pyrtl
c = pyrtl.Const(1, 1)
o = pyrtl.Output(3, 'o')
o <<= pyrtl.concat(c, c, c)
```
the logic of block is:
```python
for net in pyrtl.working_block():
print(net)
```
```bash
tmp0/3W <-- c -- const_0_1/1C, const_0_1/1C, const_0_1/1C 
o/3O <-- w -- tmp0/3W 
```
however the result of `net_graph()` previously was:
```python
for src, vals in pyrtl.net_graph().items():
for dst, edge in vals.items():
print(f"({src}) - {edge} -> ({dst})"
```
```bash
(o/3O <-- w -- tmp0/3W ) - o/3O -> (o/3O)
(tmp0/3W <-- c -- const_0_1/1C, …
```
> Be able to show multiplicity of identical edges going to a net

- pyrtl/__init__.py
- pyrtl/passes.py
- tests/test_passes.py
While writing transforms for converting PyRTL into BLIF compatible with some superconducting design tools, I found it necessary to make sure that there were no wire nets in the netlist. Part of that process involved directly connecting outputs to their sources, bypassing any intermediate `w` nets if possible. This PR provides that pass, in case others find it useful.
Given
```python
i = pyrtl.Input(2, 'i')
j = pyrtl.Input(2, 'j')
o = pyrtl.Output(4, 'o')
o <<= i * j
```
Call `pyrtl.direct_connect_outputs()` to produce
The pass makes sure that it only does this when safe (e.g. maintaining the invariant that every net has a single destination wire), only doing that change when that destination wire only goes to a single destination `w` net which in turns goes to an Output.
> Add optional pass directly connecting nets to outputs when possible

- pyrtl/__init__.py
- pyrtl/analysis.py
- pyrtl/passes.py
- tests/test_analysis.py
- tests/test_passes.py
This PR adds an optional pass (`pyrtl.two_way_fanout()`) that makes it so all wires go to at most 2 destinations. It also adds a convenient helper function called `pyrtl.fanout` for calculating the fanout of a wire.
In a future PR, it would be nice to make the maximum target fanout an argument to the function. Another nicety would be to optimize so that the first split after the original wire isn't needed.
Note the fanout of the wire coming out of `and` in this example was originally 4 but now has a tree of wires so that no fanout is greater than 2.
> Add optional pass for making all fanouts <= 2

- pyrtl/transform.py
An internal helper function within `replace_wires_fast` was using a variable declared outside of its immediate scope instead of the intended helper function argument. Since both variables aliased the same object, there was no functionality bug, but it's definitely possible that this might introduce a bug in the future if further changes are made. To make it clearer, this PR just changes the helper function to use the intended argument.
All tests still pass, and `replace_wires_fast` performs as intended.
E.g. in the following:
replacing `o` with `x` successfully produces:
(those object ids are just for visually verifying the third net object didn't change, but the first two did).
> Minor fix to replace_wires_fast

- pyrtl/visualization.py
- tests/test_visualization.py
This PR makes the Graphviz string produced by `block_to_graphviz_string` deterministic/reproducible, to make it easier for comparing changes non-visually. This doesn't change the visualization at all.
> Make graphviz string export deterministic via ordering the nodes first

- pyrtl/visualization.py
- tests/test_visualization.py
This closes #363, adding the option to make the incoming edges of a net where order matters (like '-', 'c', etc.) be ordered.
For example, given:
```python
i = pyrtl.Input(8, 'i')
j = pyrtl.Input(4, 'j')
o = pyrtl.Output(8, 'o')
q = pyrtl.Output(1, 'q')
o <<= i < j
q <<= j > i
```
Calling
```python
with open("test.gv", "w") as f:
pyrtl.output_to_graphviz(f)
```
produced:
Note how the `j` is the **second** argument of the `>` net and the **first** argument of the `<`, which is opposite of what the netlist says.
```python
with open("test.gv", "w") as f:
pyrtl.output_to_graphviz(f, maintain_arg_order=True)
```
produces:
Note how the `j` is the **first** argument of the `>` net and the **second** argument of the `<` like was specified in the user code.
I made this option default to False …
> Add option to use left-to-right ordering in Graphviz output where order of arguments matters for net

- pyrtl/rtllib/matrix.py
- tests/rtllib/test_matrix.py
This PR adds the `flatten()` method to the PyRTL matrix implementation. `flatten()` is also a method on numpy matrices, and our version supports two orders: row-wise and column-wise.
> Add flatten() method to matrices

- pyrtl/analysis.py
- tests/test_analysis.py
This PR makes sure the proper argument is being passed to the `paths()` call for the keyword argument `block`.
> Minor fix to distance() analysis function

- pyrtl/rtllib/matrix.py
- tests/rtllib/test_matrix.py
This PR fixes `flatten()` so it works for non-square matrices and adds `reshape()` and `put()` methods on the Matrix class.
> Fix Matrix, flatten(), add reshape() and put() methods

- pyrtl/rtllib/matrix.py
- tests/rtllib/test_matrix.py
There was a test helper function, `matrix_to_int` in `test_matrix.py` that converts Python lists of lists into an int. Since this is useful outside of testing (i.e. in Simulation), I moved it to `matrix.py`, renamed it, and added some more functionality (i.e. making sure it handles negative elements (converting to two's complement) and checking for a bad number of bits).
> Move and improve list_to_int helper from test_matrix.py to matrix.py file

- apt.txt
- postBuild
Since `requirements.txt` is limited solely to the packages that users need to run the normal parts of PyRTL, it does not contain the `graphviz` dependency. However, some of the Jupyter example files do require `graphviz`, and so we need a way to tell the binder to install these additional packages automatically.
Both `apt.txt` and `postBuild` are used soley by `mybinder.org` at the moment.
> Add graphviz as Binder (Jupyter) dependency

- pyrtl/rtllib/aes.py
Fixes the example in the comments of the `aes.py` file. Fixes #379.
> Update AES example

- pyrtl/core.py
- pyrtl/passes.py
- tests/test_core.py
This PR adds some sanity checks for checking the consistency of `wirevector_by_name`. This revealed a few bugs in passes where the `wirevector_by_name` dictionary was not being updated.
Also updated code’s developer notes for clarity.
> Add sanity checks for wirevector_by_name

- pyrtl/importexport.py
- tests/test_importexport.py
- tests/test_wire.py
Fixes issue where extra `else` is inserted into Verilog when `add_reset=False`.
Also adds tests just related to setting the `reset_value` in the Register initializer.
> Fix bug when add_reset=False; add Register tests

- pyrtl/corecircuits.py
- tests/test_helperfuncs.py
As I was using `bitfield_update`, I noticed an incorrect example in the documentation. This PR fixes it, adds more documented examples, and adds more unit tests for `bitfield_update` and `bitfield_update_set`.
> More tests, documentation for bitfield_update (incl. set)

- pyrtl/simulation.py
- pyrtl/visualization.py
- tests/test_simulation.py
- tests/test_visualization.py
As I've been analyzing many traces, I've found it useful to be able to specify the format that the values are represented in the wave form. I.e. I'd like to be able to specify that the numbers should be represented as hexadecimal (the default), or binary, or octal, or decimal, or some other format. This PR makes it possible by passing in a representation function to `render_trace()`. This also adds more tests.
E.g. now we get (here is the same trace printed in binary, hex, oct, and decimal one after the other), via this code:
```python
sim.tracer.render_trace(repr_func=bin, symbol_len=None)
sim.tracer.render_trace(repr_func=hex, symbol_len=None)
sim.tracer.render_trace(repr_func=oct, symbol_len=None)
sim.tracer.render_trace(repr_func=str, symbol_len=None)
```
It also works for the …
> Add ability to specify how values render in trace; improve symbol_len calculation.

- pyrtl/compilesim.py
- pyrtl/simulation.py
- tests/test_compilesim.py
- tests/test_simulation.py
There have been instances when I'd like to use the `expected_outputs` feature of `step_multiple`, but only care about the value of a wire on a certain clock cycle (e.g. when dealing with protocols, or output wires that change and whose values don't matter until a finished signal is high). This PR allows you to specify don't-cares in expected outputs via `?`. This doesn't change how we specify input values, which still require numeric values for every input for every step.
> Add ability to specify dont-cares in expected output of step_multiple

- tests/test_importexport.py
Older versions of Yosys before [this](https://github.com/YosysHQ/yosys/commit/b76b02358439cd04ed5cad5cb889e8b43c801ac1#diff-0669f85faa7b63a365d1c33676c94016e99ae7d2dc071e7e411150aa34695bf9) change only recognize `-V` for checking the version. This PR uses that flag in the tests instead for better compatiblity.
> Use `-V` for checking yosys, rather than `--version`, for more compatibility

- pyrtl/simulation.py
- tests/test_simulation.py
Given this PyRTL code:
```
import pyrtl
a, b, c = pyrtl.input_list('a/8 b/8 c/1')
o = pyrtl.Output(name='o')
o <<= a + b - c
sim.step_multiple({
'a': [1, 4, 9, 11, 12],
'b': [2, 23, 43, 120, 0],
'c': [0, 1, 1, 0, 0],
})
sim.tracer.render_trace(render_cls=pyrtl.simulation.AsciiWaveRenderer, symbol_len=None)
sim.tracer.render_trace(symbol_len=None)
```
the binary waveforms being printed didn't aligned with wires whose bitwidth > 1. This is because it was using spaces, instead of an empty string, for Ascii waveform counterparts to the Unicode reverse escape characters (which are length zero visually).
I.e. before:
(the top is the Ascii rendered version, and below it is the normal Unicode version).
After:
(again, the top is the Ascii rendered version, and below the …
> Improve binary wave form in Ascii trace render

- pyrtl/importexport.py
This improves rom verilog output by emitting the "always block" if and only if there are writes. For example, the following:
```verilog
// Memory mem_0: tmp4
always @(posedge clk)
begin
end
assign tmp29 = mem_0[tmp28];
assign tmp30 = mem_0[tmp27];
```
is now emitted as:
```verilog
// Memory mem_0: tmp4
assign tmp29 = mem_0[tmp28];
assign tmp30 = mem_0[tmp27];
```
> Improve rom verilog output

- pyrtl/importexport.py
- tests/test_importexport.py
This continues on the improvements from #399 by doing the check for memory writes _per memory_, rather than across all of them, when outputting Verilog.
I.e. instead of this (the empty `begin ... end`):
```
...
// Memory mem_0: tmp0
always @(posedge clk)
begin
end
assign tmp2 = mem_0[in1];
// Memory mem_1: tmp1
always @(posedge clk)
begin
if (const_0_1) begin
mem_1[tmp2] <= const_1_42;
end
end
...
```
these changes now cause the following to be produced:
```
...
// Memory mem_0: tmp0
assign tmp2 = mem_0[in1];
// Memory mem_1: tmp1
always @(posedge clk)
begin
if (const_0_1) begin
mem_1[tmp2] <= const_1_42;
end
end
...
```
> Improve Verilog output when a memory doesn't have any writes

- pyrtl/importexport.py
- tests/test_importexport.py
In [this commit](https://github.com/UCSBarchlab/PyRTL/commit/9dc3fdbeb5e60a0490144c82f90f30bba52ac1f6#diff-a884ba1966ff1972495efd768dbcc7e9c6b8a854adcb840d4e27e3e1117a8d42R323), I updated blif import to be a little more general, but in so doing, introduced a place where `n` (nand) nets are created. The `n` net is a non-primitive in PyRTL, and should only be introduced via a call to `nand_synth()`, and so issues come up if you import a BLIF that generates a `n`, and then try to export it to Verilog, for example, where checks are made for unsupported nets.
This PR just converts any `n` seen during BLIF import into a combination of `~` and `&`.
> Don't generate nands on BLIF import
